import { StyleSheet } from 'react-native';
import theme from '../../../CustomProps/Theme';
export default StyleSheet.create({
  container: {
    marginTop: 50,
    flex: 1,
    alignItems: 'center',
    backgroundColor: theme.backgroundColor,
  },

  thumbnail: {
    height: 300,
    width: 300,
    resizeMode: 'contain',
    alignSelf: 'center',
    margin: 20,
  },
  input: {
    backgroundColor: '#F8F5F2',
    height: 48,
    borderRadius: 5,
    overflow: 'hidden',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  buttonLarge: {
    backgroundColor: theme.colors.accent,
    marginLeft: 120,
    marginRight: 120,
    marginTop: 20,
    height: 30,
    width: 150,
    borderRadius: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonTitleLarge: theme.buttonTitleLarge,

  buttonStyle: {
    backgroundColor: '#788eec',
    marginLeft: 15,
    marginRight: 55,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  horizontal: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 30,
    marginTop: 80,
  },
  snackbar: {
    backgroundColor: '#f03a47',
    color: '#f8f5f2',
  },
  midScreenHeader: {
    // width: 100,
    height: 100,
    backgroundColor: theme.colors.cancelButton,
  },
  midScreenHeaderEdit: {
    // width: 100,
    height: 100,
    backgroundColor: theme.colors.cancelButton,
  },
  titleMidScreenHeader: {
    height: 48,
    overflow: 'hidden',
    paddingLeft: 0,
    alignSelf: 'center',
    marginTop: 50,
    fontWeight: 'bold',
    fontSize: 20,
    color: theme.colors.lightBackground,
  },
  titleMidScreenHeaderEdit: {
    height: 48,
    overflow: 'hidden',
    paddingLeft: 0,
    alignSelf: 'center',
    marginTop: 50,
    fontWeight: 'bold',
    fontSize: 20,
    color: theme.colors.lightBackground,
  },
});
